/* Automatically generated by configure - do not modify */
#define CONFIG_QEMU_SHAREDIR "/c/Program Files/Qemu"
#define HOST_I386 1
#define HOST_LONG_BITS 32
#define CONFIG_WIN32 1
#define CONFIG_GDBSTUB 1
#define CONFIG_SLIRP 1
#define QEMU_VERSION "0.9.0"
#define CONFIG_UNAME_RELEASE ""
