set(CMAKE_C_COMPILER "clang")
set(CMAKE_CXX_COMPILER "clang++")
set(CMAKE_C_COMPILER_TARGET "aarch64-apple-darwin")
set(CMAKE_CXX_COMPILER_TARGET "aarch64-apple-darwin")
set(CMAKE_OSX_ARCHITECTURES "arm64" CACHE STRING "")
