/* Automatically generated by configure - do not modify */
#include "config-host.h"
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-i386"
#define TARGET_ARCH "i386"
#define TARGET_I386 1
#define USE_KQEMU 1
#define CONFIG_SOFTMMU 1
#define CONFIG_SDL 1
#define HAVE_STRDUP 1
