/*
 * 86Box    A hypervisor and IBM PC system emulator that specializes in
 *          running old operating systems and software designed for IBM
 *          PC systems and compatibles from 1981 through fairly recent
 *          system designs based on the PCI bus.
 *
 *          This file is part of the 86Box distribution.
 *
 *          Definitions for the QIC-117 "floppy tape" drive emulation.
 *          Refer to the QIC-117 spec:
 *          https://www.qic.org/html/standards/11x.x/qic117j.pdf
 *
 *          A floppy tape drive hangs off the very same ribbon cable as
 *          the regular floppy drives and occupies one of the four drive
 *          select lines. Data is transferred with ordinary FDC READ and
 *          WRITE DATA commands, while the drive itself is commanded by
 *          counting the step pulses generated by FDC SEEK commands, as
 *          laid out in the QIC-117 common command set.
 *
 * Authors: Dmitry Brant, <me@dmitrybrant.com>
 *
 *          Copyright 2026 Dmitry Brant
 */
#ifndef EMU_FDD_TAPE_H
#define EMU_FDD_TAPE_H

/* For logging detailed QIC-117 debugging into the emulator log. */
#if 0
#    define ENABLE_FDD_TAPE_LOG 1
#endif

/*
   QIC-40/80 tape layout, as seen through the floppy controller. A segment
   is the unit the host reads and writes in, and is made up of 32 sectors
   of 1024 bytes. Segments are mapped onto the C/H/R address space of the
   floppy controller with a fixed geometry of four segments per cylinder
   and 255 cylinders per head.
 */
#define FDD_TAPE_SECTOR_SIZE     1024
#define FDD_TAPE_SECTORS_PER_SEG 32
#define FDD_TAPE_SEGMENT_SIZE    (FDD_TAPE_SECTOR_SIZE * FDD_TAPE_SECTORS_PER_SEG)
/*
   Defaults only. The cartridge's own header segment states the mapping it
   was formatted with, and a QIC-80 tape typically uses 150 cylinders per
   head rather than the 255 these defaults imply.
 */
#define FDD_TAPE_SEGS_PER_CYL    4
#define FDD_TAPE_SEGS_PER_HEAD   1020

/* Highest cylinder a data transfer may name in the C/H/R address space. */
#define FDD_TAPE_MAX_TRACK       255

#ifdef __cplusplus
extern "C" {
#endif

extern int  fdd_tape_enabled;                   /* drive fitted to the cable */
extern int  fdd_tape_unit;                      /* drive select line, 0..3 */
extern char fdd_tape_fn[MAX_IMAGE_PATH_LEN];    /* cartridge image */

/* Attaches or detaches the drive according to the configuration above. */
extern void fdd_tape_init(void);
extern void fdd_tape_close(void);

/* Loads a cartridge image into the drive, or ejects it when fn is empty. */
extern void fdd_tape_load(const char *fn);
extern void fdd_tape_eject(void);

extern void fdd_tape_set_fdc(void *fdc);

/* Adds a burst of step pulses to the train in progress, and returns how
   long the controller needs to clock them out, in microseconds. */
extern int fdd_tape_step(int drive, int steps);

/* Queries used by the floppy drive and controller layers. */
extern int fdd_tape_present(int drive);
extern int fdd_tape_track0(int drive);
extern int fdd_tape_get_flags(int drive);

#ifdef __cplusplus
}
#endif

#endif /*EMU_FDD_TAPE_H*/
