/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "networkmessage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Fragment, Fragment, AUTO)


PB_BIND(Ack, Ack, AUTO)


PB_BIND(NetworkMessage, NetworkMessage, AUTO)




